name: "Dependabot reviewer"
permissions:
  contents: write
  pull-requests: write
on: pull_request

jobs:
  shared-workflows:
    uses: Sundsvallskommun/.github/.github/workflows/common-dependabot-reviewer.yml@main
    secrets: inherit
